sudo: false
language: go
go:
- 1.6.2
install:
- go get -u github.com/kardianos/govendor
- govendor sync
script: go test ./...
deploy:
  provider: heroku
  app:
    master: snap-plugin-webapi-staging
    production: snap-plugin-webapi
  api_key:
    secure: c4PZM18R+noz4OAPS748qVnK7SMd1vwJtEeSNCq//v8RPThwW1e9cTA7u+pNDg74L8LlNIrrjjVrmsrWe5zFEURjTtDAK9Rmaa90VcMwCdsGIhIdnYTJN0G8VhEOCa5LM8Na4sRZUe9/0CyhuW0d6KrvOZiB2zLwdASxjMr59inGzKXa7QHF/q80cYlJC35tpNpDUTHO1zMCudkjdhgWRV3G7NDwNT/EF25EbYZh+oN02won/hJ4kX5OOBcTI1fxgtMhKvzSSp1cIvcIKUtr01mdVflyu5PGyH2cpQ2tGaqZ1TjnAdXQOioyJotr1RxEnD8wPrbOLHEsLaHjb25B7hdy5Fae2XSdYsNvHj1t2lEB4c4TMloTPwmAjJVx0FgrS4G/ER9WWqDrLkAv74Ap1h1E3FNaG1a38gyltPyLTrgHgAlgiP3JK/v2eaKeij5Jk1BNTtMhD52A81LHUKWS64WgDncJ+mfp/+fbt9hRTZlkRydzbsdeP7nFVJ1ttBCKGd1jEl2rgc1ifLh5QYhFlTzQPdOopZ/yU7t8WJOHhAoE4QIukWUmu+xljkYupRVTMDLaB9JHNDKZI6IvlVdl+gt83Afj9pUzr8xFIkBbOPwYAWOC43EkoB3hBBwAH9UlWMSQz1gYoPktK31qcDNqnx9yTh2RrMj50ke3hjHYhGI=
notifications:
  email: false
  slack:
    secure: ELKEJX9SmlQl/GJM4Azd+KscDyIWYKMFC8hL+Ym38Xu4PWI/z38n7gnhlMrvHbk8CUEfyOu0Tv1TG+u2dH2t9Se39bIg8CJm32B7sG36f3h0uraSK2IMcR3x/58dXihU0I32AANvqv6aweDpO8LVKoTP8h8vIDfvIXBn82vUd+JZha6IeyfpsXXPJ019HjOXaxIU3+DNrnQ28NDLEfZvvAx20kb+WvllUXpCYPyCyMJ0AsW6hFTVeFChy/Fu8mVyZqPMRVilUZcfvTHDLQ91Aa0uMlaaelEq1g0qJ4bRObH73NU7iWQJMzz52jbdm9XSAHEPeU2B8ubmUQckhsGaIBC6qK4mg8mhPDcO1aYop5bZea6eMijgUlfHNyG8LsJedtTs5g+CLm0r99b4QYywt4jHqag/P7sbwS0K/yE5tcRjwJfWdbtx3womMRuAUoL0oqL5l74cTJ9PqvaMguZlo+fbHdFNW+ixeIjQZDwzycub8rgHhQPbM2cVTvDBgliHZKBcy45fpl9donA1OrVSrG3mR+9OlH4mhenDfjXjqlDL3umEuMT3nMySf4SEGHQXBJaEHiI8L/kMQ8HTpVCaSyvcfzzhHgdJ8SATRVOV+YWK4dV+LjAbCCdpIomI4Qd0Fz+JIMGap45Kk8u/ItxYhgsfbuSqTIS6Y8qIS8OhNm8=
